TEXT_01     Versión en Español generada por <b>ndoc</b>
TEXT_02     Funciones
TEXT_03     Tipos y Constantes
TEXT_04     Enero
TEXT_05     Febrero
TEXT_06     Marzo
TEXT_07     Abril
TEXT_08     Mayo
TEXT_09     Junio
TEXT_10     Julio
TEXT_11     Agosto
TEXT_12     Septiembre
TEXT_13     Octubre
TEXT_14     Noviembre
TEXT_15     Diciembre
TEXT_16     Aviso Legal
TEXT_17     spanish
TEXT_18     Listado
TEXT_19     Figura
TEXT_20     Tabla
TEXT_21     Fórmula
TEXT_22     Este libro se ha editado en \\LaTeX generado automáticamente por \\textbf{ndoc}.
TEXT_23     Versión
TEXT_24     Retorna
TEXT_25     Observaciones
TEXT_26     Referencia de la librería
TEXT_27     Cabecera
